/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiChatDialog: typeof import('./components/mock/AiChatDialog.vue')['default']
    Alert: typeof import('./components/ui/alert/Alert.vue')['default']
    AlertDescription: typeof import('./components/ui/alert/AlertDescription.vue')['default']
    AlertTitle: typeof import('./components/ui/alert/AlertTitle.vue')['default']
    Button: typeof import('./components/ui/button/Button.vue')['default']
    Checkbox: typeof import('./components/ui/checkbox/Checkbox.vue')['default']
    CollectionTree: typeof import('./components/mock/sidebar/CollectionTree.vue')['default']
    Dialog: typeof import('./components/ui/dialog/Dialog.vue')['default']
    DialogContent: typeof import('./components/ui/dialog/DialogContent.vue')['default']
    DialogHeader: typeof import('./components/ui/dialog/DialogHeader.vue')['default']
    DialogTrigger: typeof import('./components/ui/dialog/DialogTrigger.vue')['default']
    EndpointEditor: typeof import('./components/mock/workbench/EndpointEditor.vue')['default']
    EnvManager: typeof import('./components/mock/EnvManager.vue')['default']
    FormDataTable: typeof import('./components/mock/shared/FormDataTable.vue')['default']
    HistoryDetailDialog: typeof import('./components/mock/HistoryDetailDialog.vue')['default']
    HistoryPanel: typeof import('./components/mock/HistoryPanel.vue')['default']
    HistorySidebar: typeof import('./components/mock/sidebar/HistorySidebar.vue')['default']
    IconBar: typeof import('./components/mock/sidebar/IconBar.vue')['default']
    ImportExport: typeof import('./components/mock/ImportExport.vue')['default']
    Input: typeof import('./components/ui/input/Input.vue')['default']
    JsonHighlight: typeof import('./components/mock/shared/JsonHighlight.vue')['default']
    KeyValueTable: typeof import('./components/mock/shared/KeyValueTable.vue')['default']
    Label: typeof import('./components/ui/label/Label.vue')['default']
    MockRuleEditor: typeof import('./components/mock/workbench/MockRuleEditor.vue')['default']
    MockServerControl: typeof import('./components/mock/workbench/MockServerControl.vue')['default']
    MonacoEditor: typeof import('./components/mock/shared/MonacoEditor.vue')['default']
    RequestPanel: typeof import('./components/mock/workbench/RequestPanel.vue')['default']
    ResponseViewer: typeof import('./components/mock/workbench/ResponseViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/ui/select/Select.vue')['default']
    SettingsSidebar: typeof import('./components/mock/sidebar/SettingsSidebar.vue')['default']
    Tabs: typeof import('./components/ui/tabs/Tabs.vue')['default']
    TabsContent: typeof import('./components/ui/tabs/TabsContent.vue')['default']
    TabsList: typeof import('./components/ui/tabs/TabsList.vue')['default']
    TabsTrigger: typeof import('./components/ui/tabs/TabsTrigger.vue')['default']
    Toast: typeof import('./components/ui/toast/Toast.vue')['default']
    Toaster: typeof import('./components/ui/toast/Toaster.vue')['default']
    TreeItem: typeof import('./components/mock/sidebar/TreeItem.vue')['default']
  }
}
